name: UBS Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /srv/www/usb
          sudo git stash
          sudo git pull origin main
          sudo git stash pop
          sudo systemctl stop usbUploader
          sudo rm main
          sudo go build main.go
          sudo systemctl start usbUploader
